### ISSUE TITLE
通过 File 获取的路径和系统数据库路径格式不一样

### ISSUE THREAD

**Issue by sonichy** [binkery/python_markdown_to_html#1]
https://binkery.com/archives/401.html
经过试验发现，通过 File 获取的路径和系统数据库路径格式不一样，需要转换：
```
path = path.replace("/sdcard/", Environment.getExternalStorageDirectory().getPath() + "/");
```

**Comment by binkery** [comment]
> https://binkery.com/archives/401.html
> 经过试验发现，通过 File 获取的路径和系统数据库路径格式不一样，需要转换：
> 
> ```
> path = path.replace("/sdcard/", Environment.getExternalStorageDirectory().getPath() + "/");
> ```

您能找到这个地方来～～ 在  query 的方法里，确实没有对 path 进行处理。
